<?php

return [
    '101' => [
        ['1' => 'ELEMENTARY SCHOOL'],
        ['2' => 'JUNIOR HIGH SCHOOL'],
        ['3' => 'SENIOR HIGH SCHOOL'],
        ['4' => 'DIPLOMA'],
        ['5' => 'BACHELOR'],
        ['6' => 'MASTER'],
        ['7' => 'PHILOSOPHY OF DOCTOR'],
        ['8' => 'OTHERS'],
    ],
    '201' => [
        ['1' => 'TRADING & INDUSTRY'],
        ['2' => 'FORESTRY'],
        ['3' => 'MINING & ENERGY'],
        ['4' => 'PUBLIC WORK'],
        ['5' => 'FARMING'],
        ['6' => 'RELIGION'],
        ['7' => 'BANK & FINANCIAL'],
        ['8' => 'HEALTH & SOCIETY'],
        ['9' => 'TOURISM'],
        ['10' => 'TRANSPORTATION & COMMUNICATION'],
        ['11' => 'CULTURE & EDUCATION'],
        ['12' => 'OTHERS'],
    ],
    '301' => [
        ['1' => 'KEPALA KELUARGA/HEAD OF FAMILY'],
        ['2' => 'SUAMI/HUSBAND'],
        ['3' => 'ISTRI/WIFE'],
        ['4' => 'ANAK/CHILD'],
        ['5' => 'MENANTU/CHILD IN LAW'],
        ['6' => 'CUCU/GRAND CHILD'],
        ['7' => 'ORANG TUA/PARENT'],
        ['8' => 'MERTUA/PARENT IN LAW'],
        ['9' => 'FAMILI LAIN/RELATIVE'],
        ['10' => 'PEMBANTU/HOUSEMADE'],
        ['11' => 'OTHERS'],
    ],
    '401' => [
        ['1' => 'A'],
        ['2' => 'B'],
        ['3' => 'AB'],
        ['4' => 'O'],
        ['5' => 'A+'],
        ['6' => 'A-'],
        ['7' => 'B+'],
        ['8' => 'B-'],
        ['9' => 'AB+'],
        ['10' => 'AB-'],
        ['11' => 'O+'],
        ['12' => 'O-'],
        ['13' => 'TIDAK TAHU/UNKNOWN'],
    ],
    '501' => [
        ['1' => 'KITAS/LIMITED STAY PERMIT CARD'],
        ['2' => 'KITAP/PERMANENT STAY PERMIT CARD'],
    ],
    '601' => [
        ['1' => 'INTERNATIONAL ORGANIZATION'],
        ['2' => 'GOVERNMENT'],
        ['3' => 'COMPANY'],
        ['4' => 'PERSONAL'],
        ['5' => 'NONE'],
    ],
    '701' => [
        ['1' => 'SINGLE'],
        ['2' => 'MARRIED'],
        ['3' => 'DIVORCED'],
    ],
    '801' => [
        ['1' => 'MALE'],
        ['2' => 'FEMALE'],
    ],
    '901' => [
        ['1' => 'ISLAM'],
        ['2' => 'CHRISTIAN'],
        ['3' => 'CATHOLIC'],
        ['4' => 'HINDU'],
        ['5' => 'BUDDHISM'],
        ['6' => 'KHONG HUCU'],
        ['7' => 'OTHERS'],
    ],
];
