<?php

return [
    "101" => [
        ["1" => "TIDAK/BELUM SEKOLAH"],
        ["2" => "BELUM TAMAT SD/SEDERAJAT"],
        ["3" => "TAMAT SD/SEDERAJAT"],
        ["4" => "SLTP/SEDERAJAT"],
        ["5" => "SLTA/SEDERAJAT"],
        ["6" => "DIPLOMA I/II"],
        ["7" => "AKADEMI/DIPLOMA III/SARJANA MUDA"],
        ["8" => "DIPLOMA IV/STRATA I"],
        ["9" => "STRATA-II"],
        ["10" => "STRATA-III"],
    ],
    "102" => [
        ["1" => "MEMBENTUK RUMAH TANGGA BARU"],
        ["2" => "PINDAH TEMPAT TINGGAL"],
    ],
    "103" => [
        ["1" => "KK DIBAWA PINDAH OLEH KEP. KEL"],
        ["2" => "PINDAH TEMPAT TINGGAL TIDAK MEMBAWA KK"],
        ["3" => "PINDAH TEMPAT TINGGAL"],
    ],
    "104" => [
        ["1" => "BELUM DIBERDAYAKAN"],
        ["2" => "SEDANG DIBERDAYAKAN"],
        ["3" => "SUDAH DIBERDAYAKAN"],
    ],
    "105" => [
        ["1" => "PEKERJAAN"],
        ["2" => "PENDIDIKAN"],
        ["3" => "KEAMANAN"],
        ["4" => "KESEHATAN"],
        ["5" => "PERUMAHAN"],
        ["6" => "KELUARGA"],
        ["7" => "LAIN-LAIN"],
    ],
    "106" => [
        ["1" => "DALAM SATU DESA/KELURAHAN"],
        ["2" => "ANTAR DESA/KELURAHAN"],
        ["3" => "ANTAR KECAMATAN"],
        ["4" => "ANTAR KAB/KOTA"],
        ["5" => "ANTAR PROVINSI"],
    ],
    "107" => [
        ["1" => "KEP. KELUARGA"],
        ["2" => "KEP. KEL. DAN SELURUH ANGG. KELUARGA"],
        ["3" => "KEP.KEL DAN SBG. ANGG. KELUARGA"],
        ["4" => "ANGG.KELUARGA"],
    ],
    "108" => [
        ["1" => "BENCANA SOSIAL"],
        ["2" => "BENCANA ALAM"],
    ],
    "109" => [
        ["1" => "BARAK"],
        ["2" => "CAMP"],
        ["3" => "RUMAH"],
    ],
    "110" => [
        ["1" => "PENDUDUK TETAP"],
        ["2" => "PENDUDUK TIDAK TETAP"],
    ],
    "111" => [
        ["1" => "KONTRAK"],
        ["2" => "TIDAK MENENTU/EMPERAN TOKO"],
        ["3" => "RUMAH SINGGAH/RUMAH PENGAMPU"],
        ["4" => "KOLONG JEMBATAN"],
    ],
    "112" => [
        ["1" => "KESALAHAN ENTRI DATA"],
        ["2" => "DUPLIKASI DATA"],
        ["3" => "DATA LATIHAN"],
        ["999" => "LAINNYA"],
    ],
    "113" => [
        ["1" => "KESALAHAN HAPUS DATA"],
        ["2" => "KETIDAKSENGAJAAN"],
        ["999" => "LAINNYA"],
    ],
    "114" => [
        ["1" => "KESALAHAN ENTRI DATA KEMATIAN"],
        ["999" => "LAINNYA"],
    ],
    "115" => [
        ["1" => "DATA TIDAK ADA DI PELAYANAN"],
        ["999" => "LAINNYA"],
    ],
    "116" => [
        ["1" => "DATA TIDAK ADA PADA PELAYANAN"],
        ["999" => "LAINNYA"],
    ],
    "117" => [
        ["1" => "TIDAK AKTIF DIATAS 5 TAHUN"],
        ["2" => "PELANGGARAN HUKUM"],
        ["99" => "LAINNYA"],
    ],
    "161" => [
        ["1" => "NUMPANG KK"],
        ["2" => "MEMBUAT KK BARU"],
        ["3" => "NOMOR KK TETAP"],
    ],
    "201" => [
        ["1" => "BELUM/TIDAK BEKERJA"],
        ["2" => "MENGURUS RUMAH TANGGA"],
        ["3" => "PELAJAR/MAHASISWA"],
        ["4" => "PENSIUNAN"],
        ["5" => "PEGAWAI NEGERI SIPIL (PNS)"],
        ["6" => "TENTARA NASIONAL INDONESIA (TNI)"],
        ["7" => "KEPOLISIAN RI (POLRI)"],
        ["8" => "PERDAGANGAN"],
        ["9" => "PETANI/PEKEBUN"],
        ["10" => "PETERNAK"],
        ["11" => "NELAYAN/PERIKANAN"],
        ["12" => "INDUSTRI"],
        ["13" => "KONSTRUKSI"],
        ["14" => "TRANSPORTASI"],
        ["15" => "KARYAWAN SWASTA"],
        ["16" => "KARYAWAN BUMN"],
        ["17" => "KARYAWAN BUMD"],
        ["18" => "KARYAWAN HONORER"],
        ["19" => "BURUH HARIAN LEPAS"],
        ["20" => "BURUH TANI/PERKEBUNAN"],
        ["21" => "BURUH NELAYAN/PERIKANAN"],
        ["22" => "BURUH PETERNAKAN"],
        ["23" => "PEMBANTU RUMAH TANGGA"],
        ["24" => "TUKANG CUKUR"],
        ["25" => "TUKANG LISTRIK"],
        ["26" => "TUKANG BATU"],
        ["27" => "TUKANG KAYU"],
        ["28" => "TUKANG SOL SEPATU"],
        ["29" => "TUKANG LAS/PANDAI BESI"],
        ["30" => "TUKANG JAHIT"],
        ["31" => "TUKANG GIGI"],
        ["32" => "PENATA RIAS"],
        ["33" => "PENATA BUSANA"],
        ["34" => "PENATA RAMBUT"],
        ["35" => "MEKANIK"],
        ["36" => "SENIMAN"],
        ["37" => "TABIB"],
        ["38" => "PARAJI"],
        ["39" => "PERANCANG BUSANA"],
        ["40" => "PENTERJEMAH"],
        ["41" => "IMAM MASJID"],
        ["42" => "PENDETA"],
        ["43" => "PASTOR"],
        ["44" => "WARTAWAN"],
        ["45" => "USTADZ/MUBALIGH"],
        ["46" => "JURU MASAK"],
        ["47" => "PROMOTOR ACARA"],
        ["48" => "ANGGOTA DPR RI"],
        ["49" => "ANGGOTA DPD RI"],
        ["50" => "ANGGOTA BPK"],
        ["51" => "PRESIDEN"],
        ["52" => "WAKIL PRESIDEN"],
        ["53" => "ANGGOTA MAHKAMAH KONSTITUSI"],
        ["54" => "ANGGOTA KABINET KEMENTRIAN"],
        ["55" => "DUTA BESAR"],
        ["56" => "GUBERNUR"],
        ["57" => "WAKIL GUBERNUR"],
        ["58" => "BUPATI"],
        ["59" => "WAKIL BUPATI"],
        ["60" => "WALIKOTA"],
        ["61" => "WAKIL WALIKOTA"],
        ["62" => "ANGGOTA DPRD PROP."],
        ["63" => "ANGGOTA DPRD KAB./KOTA"],
        ["64" => "DOSEN"],
        ["65" => "GURU"],
        ["66" => "PILOT"],
        ["67" => "PENGACARA"],
        ["68" => "NOTARIS"],
        ["69" => "ARSITEK"],
        ["70" => "AKUNTAN"],
        ["71" => "KONSULTAN"],
        ["72" => "DOKTER"],
        ["73" => "BIDAN"],
        ["74" => "PERAWAT"],
        ["75" => "APOTEKER"],
        ["76" => "PSIKIATER/PSIKOLOG"],
        ["77" => "PENYIAR TELEVISI"],
        ["78" => "PENYIAR RADIO"],
        ["79" => "PELAUT"],
        ["80" => "PENELITI"],
        ["81" => "SOPIR"],
        ["82" => "PIALANG"],
        ["83" => "PARANORMAL"],
        ["84" => "PEDAGANG"],
        ["85" => "PERANGKAT DESA"],
        ["86" => "KEPALA DESA"],
        ["87" => "BIARAWAN/BIARAWATI"],
        ["88" => "WIRASWASTA"],
        ["89" => "ANGGOTA LEMBAGA TINGGI LAINNYA"],
        ["90" => "ARTIS\r\n"],
        ["91" => "ATLIT"],
        ["92" => "CHEFF"],
        ["93" => "MANAJER"],
        ["94" => "TENAGA TATA USAHA"],
        ["95" => "OPERATOR"],
        ["96" => "PEKERJA PENGOLAHAN KERAJINAN"],
        ["97" => "TEKNISI"],
        ["98" => "ASISTEN AHLI"],
        ["999" => "PEKERJAAN LAINNYA"],
    ],
    "301" => [
        ["1" => "KEPALA KELUARGA"],
        ["2" => "SUAMI"],
        ["3" => "ISTRI"],
        ["4" => "ANAK"],
        ["5" => "MENANTU"],
        ["6" => "CUCU"],
        ["7" => "ORANG TUA"],
        ["8" => "MERTUA"],
        ["9" => "FAMILI LAIN"],
        ["10" => "PEMBANTU"],
        ["11" => "LAINNYA"],
    ],
    "401" => [
        ["1" => "A"],
        ["2" => "B"],
        ["3" => "AB"],
        ["4" => "O"],
        ["5" => "A+"],
        ["6" => "A-"],
        ["7" => "B+"],
        ["8" => "B-"],
        ["9" => "AB+"],
        ["10" => "AB-"],
        ["11" => "O+"],
        ["12" => "O-"],
        ["13" => "TIDAK TAHU"],
    ],
    "501" => [
        ["1" => "ISLAM"],
        ["2" => "KRISTEN"],
        ["3" => "KATHOLIK"],
        ["4" => "HINDU"],
        ["5" => "BUDDHA"],
        ["6" => "KHONGHUCU"],
        ["7" => "KEPERCAYAAN TERHADAP TUHAN YME"],
    ],
    "511" => [
        ["1" => "ISLAM"],
        ["2" => "KRISTEN"],
        ["3" => "KATHOLIK"],
        ["4" => "HINDU"],
        ["5" => "BUDDHA"],
        ["6" => "KHONGHUCU"],
        ["7" => "KEPERCAYAAN"],
        ["8" => "LAINNYA"],
    ],
    "601" => [
        ["1" => "BELUM KAWIN"],
        ["2" => "KAWIN"],
        ["3" => "CERAI HIDUP"],
        ["4" => "CERAI MATI"],
    ],
    "602" => [
        ["1" => "PN"],
        ["2" => "PTN"],
        ["3" => "MA"],
    ],
    "603" => [
        ["1" => "SUAMI"],
        ["2" => "ISTRI"],
        ["3" => "KELUARGA"],
        ["4" => "PEJABAT"],
    ],
    "604" => [
        ["1" => "SUAMI"],
        ["2" => "ISTRI"],
        ["3" => "KESEPAKATAN SUAMI/ISTRI"],
    ],
    "611" => [
        ["1" => "UMUM"],
        ["2" => "TERLAMBAT"],
    ],
    "612" => [
        ["1" => "RUMAH SAKIT/BERSALIN"],
        ["2" => "PUSKESMAS"],
        ["3" => "POLINDES"],
        ["4" => "RUMAH"],
        ["5" => "LAINNYA"],
    ],
    "613" => [
        ["1" => "DOKTER"],
        ["2" => "BIDAN/PERAWAT"],
        ["3" => "DUKUN"],
        ["4" => "LAINNYA"],
    ],
    "614" => [
        ["1" => "TUNGGAL"],
        ["2" => "KEMBAR DUA"],
        ["3" => "KEMBAR TIGA"],
        ["4" => "KEMBAR EMPAT"],
        ["5" => "KEMBAR BANYAK/LAINNYA"],
    ],
    "615" => [
        ["1" => "WARGA NEGARA INDONESIA"],
        ["2" => "WARGA NEGARA ASING"],
    ],
    "616" => [
        ["1" => "EROPA"],
        ["2" => "CINA/TIMUR ASING LAINNYA"],
        ["3" => "INDONESIA"],
        ["4" => "INDONESIA NASRANI"],
        ["5" => "LAINNYA"],
    ],
    "617" => [
        ["1" => "SAKIT BIASA/TUA"],
        ["2" => "PANDEMI/WABAH PENYAKIT"],
        ["3" => "KECELAKAAN"],
        ["4" => "KRIMINALITAS"],
        ["5" => "BUNUH DIRI"],
        ["6" => "LAINNYA"],
    ],
    "618" => [
        ["1" => "DOKTER"],
        ["2" => "TENAGA KESEHATAN"],
        ["3" => "KEPOLISIAN"],
        ["4" => "LAINNYA"],
    ],
    "619" => [
        ["1" => "DALAM DOMISILI"],
        ["2" => "LUAR DOMISILI"],
    ],
    "620" => [
        ["1" => "PENGADILAN NEGERI"],
        ["2" => "PENGADILAN AGAMA"],
        ["3" => "PENGADILAN TINGGI NEGERI"],
        ["4" => "PENGADILAN TINGGI AGAMA"],
        ["5" => "MAHKAMAH AGUNG"],
    ],
    "621" => [
        ["1" => "BERBUAT ZINA"],
        ["2" => "PEMABUK/PEMADAT"],
        ["3" => "PENJUDI"],
        ["4" => "MENINGGALKAN PASANGAN LEBIH DARI 2 THN TANPA ALASAN"],
        ["5" => "HUKUMAN PENJARA DIATAS 5 THN/LEBIH BERAT"],
        ["6" => "MELAKUKAN KEKEJAMAN/KEKERASAN DALAM RUMAH TANGGA"],
        ["7" => "MENDAPAT CACAT BADAN/PENYAKIT"],
        ["8" => "PERSELISIHAN/PERTENGKARAN TERUS MENERUS"],
        ["9" => "LAINNYA"],
    ],
    "622" => [
        ["1" => "DOKTER"],
        ["2" => "BIDAN / PERAWAT"],
        ["3" => "TENAGA KESEHATAN LAIN"],
        ["4" => "KEPOLISIAN"],
        ["5" => "LAINNYA"],
    ],
    "623" => [
        ["1" => "SUAMI ISTRI"],
        ["2" => "SEORANG IBU"],
        ["3" => "TIDAK DIKETAHUI ORTUNYA"],
    ],
    "624" => [
        ["1" => "ORANG TUA KANDUNG"],
        ["2" => "ORANG TUA ANGKAT"],
        ["3" => "SAUDARA"],
        ["4" => "ORANG TUA TIRI"],
        ["5" => "ORANG LAIN"],
        ["6" => "INSTITUSI"],
    ],
    "625" => [
        ["1" => "ANAK SAH"],
        ["2" => "ANAK ANGKAT"],
        ["3" => "ANAK SEORANG IBU"],
        ["4" => "ANAK YANG DIAKUI MELALUI PENGAKUAN ANAK"],
    ],
    "626" => [
        ["1" => "KAWIN SAH"],
        ["2" => "TIDAK KAWIN"],
    ],
    "627" => [
        ["1" => "SUAMI"],
        ["2" => "ISTRI"],
    ],
    "628" => [
        ["1" => "PERMOHONAN KEWARGANEGARAAN"],
        ["2" => "PERKAWINAN (PASAL 19 UU NO. 12/2006)"],
    ],
    "701" => [
        ["1" => "DISABILITAS FISIK"],
        ["2" => "DISABILITAS NETRA/BUTA"],
        ["3" => "DISABILITAS RUNGU/WICARA"],
        ["4" => "DISABILITAS MENTAL/JIWA"],
        ["5" => "DISABILITAS FISIK DAN MENTAL"],
        ["6" => "DISABILITAS LAINNYA"],
    ],
    "801" => [
        ["1" => "LAKI-LAKI"],
        ["2" => "PEREMPUAN"],
    ],
    "802" => [
        ["1" => "HIDUP"],
        ["2" => "MENINGGAL DUNIA"],
        ["3" => "TANPA KETERANGAN"],
    ],
    "851" => [
        ["1" => "PENDIDIKAN"],
        ["2" => "PEKERJAAN"],
        ["3" => "KEAMANAN"],
        ["4" => "KESEHATAN"],
        ["5" => "KELUARGA"],
        ["6" => "LAIN-LAIN"],
    ],
    "901" => [
        ["1" => "PEKERJAAN"],
        ["2" => "PENDIDIKAN"],
        ["3" => "KEAMANAN"],
        ["4" => "KESEHATAN"],
        ["5" => "PERUMAHAN"],
        ["6" => "KELUARGA"],
        ["7" => "LAINNYA"],
    ],
    "911" => [
        ["1" => "INDUSTRI/PERDAGANGAN"],
        ["2" => "KEHUTANAN/PERKEBUNAN"],
        ["3" => "PERTAMBANGAN/ENERGI"],
        ["4" => "PEKERJAAN UMUM/KONSTRUKSI"],
        ["5" => "PERTANIAN/PETERNAKAN/PERIKANAN"],
        ["6" => "KEAGAMAAN"],
        ["7" => "KEUANGAN/PERBANKAN"],
        ["8" => "KESEHATAN/SOSIAL"],
        ["9" => "PARIWISATA"],
        ["10" => "TRANSPORTASI/KOMUNIKASI"],
        ["11" => "PENDIDIKAN/KEBUDAYAAN"],
        ["12" => "JASA DAN LAINNYA"],
    ],
    "912" => [
        ["1" => "PERUBAHAN ELEMEN BIODATA"],
        ["2" => "PERUBAHAN DOMISILI/ALAMAT"],
        ["99" => "LAINNYA"],
    ],
    "913" => [
        ["1" => "PERUBAHAN ANGGOTA KELUARGA"],
        ["2" => "PERUBAHAN DOMISILI/ALAMAT"],
        ["99" => "LAINNYA"],
    ]
];
